### ISSUE TITLE
Remove serveStatic

### ISSUE THREAD

**Issue by tshemsedinov** [AliusDieMorietur/course-work#2]
You need not this function `serveStatic(entryPoint, staticPath, port, mimeTypes, errorFunction)` because all arguments are just constants and function is not exported, so you call it once in certain place.

**Comment by AliusDieMorietur** [comment]
@tshemsedinov This function was removed. The way to serve static changed. You can check it [here](https://github.com/AliusDieMorietur/course-work/blob/master/server/server.js)
